### ISSUE TITLE
Can't save dashboard settings + "Invalid class" warning on app enable

### ISSUE THREAD

**Issue by dougti** [nextcloud/dashboard#17]
Hi,
 When I enable the dashboard, the following warnings appear in my log:
`
[owncloud][no app in context][3] Admin section instance must implement \OCP\ISection. Invalid class: OCA\Dashboard\Controller\AdminController
[owncloud][no app in context][3] Admin section instance must implement \OCP\Settings\ISection. Invalid class: OCA\Dashboard\Controller\AdminController
`

Also, when I try to change the app's settings in the global admin panel, the save button does nothing. I wanted to disable the email block & reorder the others, however I'm unable to save any config changes.

NC12

Cheers!

**Comment by AlviseNicoletti** [comment]
following ...

**Comment by jzielke-nli** [comment]
Confirmed on my NC13 instalation. Log outputs:
```
{"reqId":"cSHUBz6U6dGMVbv3gjT5","level":3,"time":"2018-03-07T16:59:42+01:00","remoteAddr":"194.8.192.66","user":"nxtcadmin","app":"index","method":"POST","url":"/index.php/apps/dashboard/admin","message":"Exception: {"Exception":"OCPAppFrameworkDbDoesNotExistException","Message":"Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*dashboard_settings` WHERE id = ?"; parameters Arrayn(n    [0] => 2n)n; limit ""; offset ""","Code":0,"Trace":"#0 /var/lib/nextcloud/lib/public/AppFramework/Db/Mapper.php(359): OCPAppFrameworkDbMapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)n#1 /var/lib/nextcloud/apps/dashboard/lib/Db/DashboardSettingsMapper.php(55): OCPAppFrameworkDbMapper->findEntity('SELECT * FROM `...', Array)n#2 /var/lib/nextcloud/apps/dashboard/lib/Controller/AdminController.php(154): OCADashboardDbDashboardSettingsMapper->findOne(2)n#3 [internal function]: OCADashboardControllerAdminController->save()n#4 /var/lib/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)n#5 /var/lib/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OCAppFrameworkHttpDispatcher->executeController(Object(OCADashboardControllerAdminController), 'save')n#6 /var/lib/nextcloud/lib/private/AppFramework/App.php(115): OCAppFrameworkHttpDispatcher->dispatch(Object(OCADashboardControllerAdminController), 'save')n#7 /var/lib/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OCAppFrameworkApp::main('AdminController', 'save', Object(OCAppFrameworkDependencyInjectionDIContainer), Array)n#8 [internal function]: OCAppFrameworkRoutingRouteActionHandler->__invoke(Array)n#9 /var/lib/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OCAppFrameworkRoutingRouteActionHandler), Array)n#10 /var/lib/nextcloud/lib/base.php(998): OCRouteRouter->match('/apps/dashboard...')n#11 /var/lib/nextcloud/index.php(37): OC::handleRequest()n#12 {main}","File":"/var/lib/nextcloud/lib/public/AppFramework/Db/Mapper.php","Line":275}","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36","version":"13.0.0.14"}
```

The table is empty so it seems it's not passing a query correctly nor saving anything, leading to the described results of @dougti

**Comment by stratege1401** [comment]
nc 13.0.2 same behaviors. save is not possible

**Comment by daita** [comment]
v5.0.0 is available on the appstore

**Comment by jzielke-nli** [comment]
Seriously Nextcoud 14 is out and still the same error?
